[package]
name = "boots-cli"
version.workspace = true
edition.workspace = true

[[bin]]
name = "boots"
path = "src/main.rs"

[[bin]]
name = "cargo-boots"
path = "src/cargo.rs"

[dependencies]
boots-core.workspace = true
clap.workspace = true
anyhow.workspace = true
